"""Add Purchase table for unified license system

Revision ID: a2936e5a2d3d
Revises: a9cc13238fdf
Create Date: 2025-06-05 10:19:04.090467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2936e5a2d3d'
down_revision: Union[str, None] = 'a9cc13238fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('account_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('months', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('temporary_license', sa.String(), nullable=True),
    sa.Column('final_license', sa.String(), nullable=True),
    sa.Column('hardware_id', sa.String(), nullable=True),
    sa.Column('activation_date', sa.DateTime(), nullable=True),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_customer_email'), 'purchases', ['customer_email'], unique=False)
    op.create_index(op.f('ix_purchases_customer_name'), 'purchases', ['customer_name'], unique=False)
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.create_index(op.f('ix_purchases_order_id'), 'purchases', ['order_id'], unique=True)
    op.create_index(op.f('ix_purchases_version'), 'purchases', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_version'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_order_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_customer_name'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_customer_email'), table_name='purchases')
    op.drop_table('purchases')
    # ### end Alembic commands ###
